import {NextPage} from "next";
import Head from "next/head";

const Home: NextPage = () => {
    return (<div>
            <Head>
                <title>LinkedIn</title>
                <meta name={"description"} content={"Generated by create next app"}/>
                <link rel={"icon"} href={"/favicon.ico"}/>
            </Head>
            Hello Next.js
        </div>
    );
};

export default Home;
